version: '3.1'

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - 5432:5432
    volumes:
      - ./src/test/resources/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./src/test/resources/data.sql:/docker-entrypoint-initdb.d/02_data.sql